# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='development.HashTag'),
        ),
    ]
